### PR TITLE
Add action response modals

### PR DESCRIPTION
**Pull request by lucidlogic**
With reference to this issue https://github.com/gobrightspot/nova-detached-actions/issues/41
Nova has introduced (in version 3.21.0) custom response modals to actions. This update will allow these responses to work

### CODE REVIEW

**Comment by rdarcy1** [comment]
Wish I'd seen this before looking at it myself! 

In [my branch](https://github.com/gobrightspot/nova-detached-actions/compare/master...rdarcy1:response-modal) I've replaced the `transition` element with `portal` in line with the current Nova approach to modals. Not sure on the backwards compatibility of doing this, but I'd imagine it's going to be more future-proof.

**Comment by lucidlogic** [comment]
@rdarcy1 nice one, I prefer your way

**Comment by rdarcy1** [comment]
You're welcome to copy the changes into your PR, I didn't want to submit a duplicate.

**Comment by lucidlogic** [comment]
@rdarcy1 changes made

**Comment by lucidlogic** [comment]
@eoghanobrien any update here?

**Comment by eoghanobrien** [comment]
@lucidlogic I've left the company that sponsors this open source work, you could try reaching out to them directly to get this merged in.

**Pull request merged**
