### PR TITLE
Complete Nova 4 Update

### PR DESCRIPTION
**Pull request by the-alichemist**

### CODE REVIEW

**Comment by orlyapps** [comment]
🤟

**Comment by matthewhutchings** [comment]
{
"message": "Declaration of Brightspot\\Nova\\Tools\\DetachedActions\\DetachedAction::jsonSerialize() must be compatible with Laravel\\Nova\\Actions\\Action::jsonSerialize(): array",
"exception": "Symfony\\Component\\ErrorHandler\\Error\\FatalError",
"file": "/Users/matthewhutchings/Sites/dashboard-qcf/vendor/gobrightspot/nova-detached-actions/src/DetachedAction.php",
"line": 334,
"trace": []
}

You need to update line 334 in DetachedActiom.php to add :array

**Comment by eullercdr** [comment]
> { "message": "Declaration of Brightspot\Nova\Tools\DetachedActions\DetachedAction::jsonSerialize() must be compatible with Laravel\Nova\Actions\Action::jsonSerialize(): array", "exception": "Symfony\Component\ErrorHandler\Error\FatalError", "file": "/Users/matthewhutchings/Sites/dashboard-qcf/vendor/gobrightspot/nova-detached-actions/src/DetachedAction.php", "line": 334, "trace": [] }
> 
> You need to update line 334 in DetachedActiom.php to add :array

I am the same error. Please @gobrightspot fixed this, is very important for us. Thanks in advanced.

**Comment by eullercdr** [comment]
Please @gobrightspot create a new release, for this PR.

**Pull request merged**
